// <auto-generated />
using System;
using CardGames.Poker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardGames.Poker.Api.Migrations
{
    [DbContext(typeof(CardsDbContext))]
    partial class CardsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.BettingActionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ActionAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ActionOrder")
                        .HasColumnType("int");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid>("BettingRoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChipStackAfter")
                        .HasColumnType("int");

                    b.Property<int>("ChipStackBefore")
                        .HasColumnType("int");

                    b.Property<int>("ChipsMoved")
                        .HasColumnType("int");

                    b.Property<double?>("DecisionTimeSeconds")
                        .HasColumnType("float");

                    b.Property<Guid>("GamePlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsForced")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTimeout")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PotAfter")
                        .HasColumnType("int");

                    b.Property<int>("PotBefore")
                        .HasColumnType("int");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ActionAt");

                    b.HasIndex("BettingRoundId");

                    b.HasIndex("GamePlayerId");

                    b.HasIndex("BettingRoundId", "ActionOrder")
                        .IsUnique();

                    b.ToTable("BettingActionRecords");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.BettingRound", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrentActorIndex")
                        .HasColumnType("int");

                    b.Property<int>("CurrentBet")
                        .HasColumnType("int");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HandNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<int>("LastAggressorIndex")
                        .HasColumnType("int");

                    b.Property<int>("LastRaiseAmount")
                        .HasColumnType("int");

                    b.Property<int>("MaxRaises")
                        .HasColumnType("int");

                    b.Property<int>("MinBet")
                        .HasColumnType("int");

                    b.Property<int>("PlayersActed")
                        .HasColumnType("int");

                    b.Property<int>("PlayersInHand")
                        .HasColumnType("int");

                    b.Property<int>("RaiseCount")
                        .HasColumnType("int");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GameId", "HandNumber");

                    b.HasIndex("GameId", "HandNumber", "RoundNumber")
                        .IsUnique();

                    b.ToTable("BettingRounds");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Ante")
                        .HasColumnType("int");

                    b.Property<int?>("BigBet")
                        .HasColumnType("int");

                    b.Property<int?>("BigBlind")
                        .HasColumnType("int");

                    b.Property<int?>("BringIn")
                        .HasColumnType("int");

                    b.Property<int>("BringInPlayerIndex")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrentDrawPlayerIndex")
                        .HasColumnType("int");

                    b.Property<int>("CurrentHandNumber")
                        .HasColumnType("int");

                    b.Property<string>("CurrentPhase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CurrentPlayerIndex")
                        .HasColumnType("int");

                    b.Property<int>("DealerPosition")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GameSettings")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("GameTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MinBet")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RandomSeed")
                        .HasColumnType("int");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint");

                    b.Property<int?>("SmallBet")
                        .HasColumnType("int");

                    b.Property<int?>("SmallBlind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GameTypeId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.GameCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DealOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DealtAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DealtAtPhase")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DiscardedAtDrawRound")
                        .HasColumnType("int");

                    b.Property<int?>("DrawnAtRound")
                        .HasColumnType("int");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GamePlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HandNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsBuyCard")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDiscarded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDrawnCard")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWild")
                        .HasColumnType("bit");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint");

                    b.Property<int>("Suit")
                        .HasColumnType("int");

                    b.Property<int>("Symbol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GamePlayerId");

                    b.HasIndex("GameId", "HandNumber");

                    b.HasIndex("GameId", "HandNumber", "Location");

                    b.HasIndex("GamePlayerId", "Location", "DealOrder");

                    b.ToTable("GameCards");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.GamePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChipStack")
                        .HasColumnType("int");

                    b.Property<int>("CurrentBet")
                        .HasColumnType("int");

                    b.Property<int?>("DropOrStayDecision")
                        .HasColumnType("int");

                    b.Property<int?>("FinalChipCount")
                        .HasColumnType("int");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasDrawnThisRound")
                        .HasColumnType("bit");

                    b.Property<bool>("HasFolded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAllIn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSittingOut")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("JoinedAtHandNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LeftAtHandNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint");

                    b.Property<int>("SeatPosition")
                        .HasColumnType("int");

                    b.Property<int>("StartingChips")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalContributedThisHand")
                        .HasColumnType("int");

                    b.Property<string>("VariantState")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("GameId", "PlayerId")
                        .IsUnique();

                    b.HasIndex("GameId", "SeatPosition")
                        .IsUnique();

                    b.HasIndex("GameId", "Status");

                    b.ToTable("GamePlayers");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.GameType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BettingStructure")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("HasDrawPhase")
                        .HasColumnType("bit");

                    b.Property<int>("InitialBoardCards")
                        .HasColumnType("int");

                    b.Property<int>("InitialHoleCards")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxCommunityCards")
                        .HasColumnType("int");

                    b.Property<int>("MaxDiscards")
                        .HasColumnType("int");

                    b.Property<int>("MaxPlayerCards")
                        .HasColumnType("int");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("VariantSettings")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("WildCardRule")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("GameTypes");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastActiveAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Preferences")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint");

                    b.Property<long>("TotalChipsLost")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalChipsWon")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalGamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("TotalHandsPlayed")
                        .HasColumnType("int");

                    b.Property<int>("TotalHandsWon")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasFilter("[ExternalId] IS NOT NULL");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.Pot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("AwardedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HandNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsAwarded")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxContributionPerPlayer")
                        .HasColumnType("int");

                    b.Property<int>("PotOrder")
                        .HasColumnType("int");

                    b.Property<int>("PotType")
                        .HasColumnType("int");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint");

                    b.Property<string>("WinReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WinnerPayouts")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GameId", "HandNumber");

                    b.HasIndex("GameId", "HandNumber", "PotOrder");

                    b.ToTable("Pots");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.PotContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ContributedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("GamePlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEligibleToWin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPotMatch")
                        .HasColumnType("bit");

                    b.Property<Guid>("PotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GamePlayerId");

                    b.HasIndex("PotId");

                    b.HasIndex("PotId", "GamePlayerId")
                        .IsUnique();

                    b.ToTable("PotContributions");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.BettingActionRecord", b =>
                {
                    b.HasOne("CardGames.Poker.Api.Data.Entities.BettingRound", "BettingRound")
                        .WithMany("Actions")
                        .HasForeignKey("BettingRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardGames.Poker.Api.Data.Entities.GamePlayer", "GamePlayer")
                        .WithMany("BettingActions")
                        .HasForeignKey("GamePlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BettingRound");

                    b.Navigation("GamePlayer");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.BettingRound", b =>
                {
                    b.HasOne("CardGames.Poker.Api.Data.Entities.Game", "Game")
                        .WithMany("BettingRounds")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.Game", b =>
                {
                    b.HasOne("CardGames.Poker.Api.Data.Entities.GameType", "GameType")
                        .WithMany("Games")
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.GameCard", b =>
                {
                    b.HasOne("CardGames.Poker.Api.Data.Entities.Game", "Game")
                        .WithMany("GameCards")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardGames.Poker.Api.Data.Entities.GamePlayer", "GamePlayer")
                        .WithMany("Cards")
                        .HasForeignKey("GamePlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");

                    b.Navigation("GamePlayer");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.GamePlayer", b =>
                {
                    b.HasOne("CardGames.Poker.Api.Data.Entities.Game", "Game")
                        .WithMany("GamePlayers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardGames.Poker.Api.Data.Entities.Player", "Player")
                        .WithMany("GameParticipations")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.Pot", b =>
                {
                    b.HasOne("CardGames.Poker.Api.Data.Entities.Game", "Game")
                        .WithMany("Pots")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.PotContribution", b =>
                {
                    b.HasOne("CardGames.Poker.Api.Data.Entities.GamePlayer", "GamePlayer")
                        .WithMany("PotContributions")
                        .HasForeignKey("GamePlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CardGames.Poker.Api.Data.Entities.Pot", "Pot")
                        .WithMany("Contributions")
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GamePlayer");

                    b.Navigation("Pot");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.BettingRound", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.Game", b =>
                {
                    b.Navigation("BettingRounds");

                    b.Navigation("GameCards");

                    b.Navigation("GamePlayers");

                    b.Navigation("Pots");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.GamePlayer", b =>
                {
                    b.Navigation("BettingActions");

                    b.Navigation("Cards");

                    b.Navigation("PotContributions");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.GameType", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.Player", b =>
                {
                    b.Navigation("GameParticipations");
                });

            modelBuilder.Entity("CardGames.Poker.Api.Data.Entities.Pot", b =>
                {
                    b.Navigation("Contributions");
                });
#pragma warning restore 612, 618
        }
    }
}
