// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using CardGames.Poker.Api.Contracts;

#nullable enable annotations

namespace CardGames.Poker.Api.Clients
{
    /// <summary>CreateGame</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.7.0.0")]
    public partial interface IFiveCardDrawApi
    {
        /// <summary>CreateGame</summary>
        /// <remarks>Create a new game.</remarks>
        /// <returns>Created</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json, application/problem+json", "Content-Type: application/json")]
        [Post("/api/v1/games/five-card-draw")]
        Task<IApiResponse<System.Guid>> CreateGameAsync([Body] CreateGameCommand body, CancellationToken cancellationToken = default);

        /// <summary>GetGames</summary>
        /// <remarks>Retrieve a list of games.</remarks>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>OK</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json")]
        [Get("/api/v1/games/five-card-draw")]
        Task<IApiResponse<ICollection<GetGamesResponse>>> GetGamesAsync(CancellationToken cancellationToken = default);

        /// <summary>GetGame</summary>
        /// <remarks>Retrieve a specific game by its identifier.</remarks>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>OK</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json")]
        [Get("/api/v1/games/five-card-draw/{gameId}")]
        Task<IApiResponse<GetGameResponse>> GetGameAsync(System.Guid gameId, CancellationToken cancellationToken = default);
    }

    /// <summary>No summary available</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.7.0.0")]
    public partial interface ICardGamesPokerApiApi
    {
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>OK</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: text/plain")]
        [Get("/")]
        Task<IApiResponse<string>> AnonymousAsync(CancellationToken cancellationToken = default);
    }

}

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace CardGames.Poker.Api.Contracts
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record CreateGameCommand
    {
        [JsonConstructor]
        public CreateGameCommand(int @ante, string @gameName, int @minBet, ICollection<PlayerInfo> @players)
        {
            this.GameName = @gameName;
            this.Ante = @ante;
            this.MinBet = @minBet;
            this.Players = @players;
        }

        [JsonPropertyName("gameName")]
        public string GameName { get; init; }

        [JsonPropertyName("ante")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int Ante { get; init; }

        [JsonPropertyName("minBet")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int MinBet { get; init; }

        [JsonPropertyName("players")]
        [System.ComponentModel.DataAnnotations.Required]
        public ICollection<PlayerInfo> Players { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum GameStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"WaitingForPlayers")]
        WaitingForPlayers = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"InProgress")]
        InProgress = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"BetweenHands")]
        BetweenHands = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"Completed")]
        Completed = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"Cancelled")]
        Cancelled = 4,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record GetGameResponse
    {
        [JsonConstructor]
        public GetGameResponse(int? @ante, int? @bigBet, int? @bigBlind, int? @bringIn, int @bringInPlayerIndex, System.DateTimeOffset @createdAt, int @currentDrawPlayerIndex, int @currentHandNumber, string @currentPhase, int @currentPlayerIndex, int @dealerPosition, System.DateTimeOffset? @endedAt, string @gameSettings, System.Guid @gameTypeId, System.Guid @id, int? @minBet, string @name, int? @randomSeed, string @rowVersion, int? @smallBet, int? @smallBlind, System.DateTimeOffset? @startedAt, GameStatus @status, System.DateTimeOffset @updatedAt)
        {
            this.Id = @id;
            this.GameTypeId = @gameTypeId;
            this.Name = @name;
            this.CurrentPhase = @currentPhase;
            this.CurrentHandNumber = @currentHandNumber;
            this.DealerPosition = @dealerPosition;
            this.Ante = @ante;
            this.SmallBlind = @smallBlind;
            this.BigBlind = @bigBlind;
            this.BringIn = @bringIn;
            this.SmallBet = @smallBet;
            this.BigBet = @bigBet;
            this.MinBet = @minBet;
            this.GameSettings = @gameSettings;
            this.Status = @status;
            this.CurrentPlayerIndex = @currentPlayerIndex;
            this.BringInPlayerIndex = @bringInPlayerIndex;
            this.CurrentDrawPlayerIndex = @currentDrawPlayerIndex;
            this.RandomSeed = @randomSeed;
            this.CreatedAt = @createdAt;
            this.UpdatedAt = @updatedAt;
            this.StartedAt = @startedAt;
            this.EndedAt = @endedAt;
            this.RowVersion = @rowVersion;
        }

        [JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid Id { get; init; }

        [JsonPropertyName("gameTypeId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid GameTypeId { get; init; }

        [JsonPropertyName("name")]
        public string Name { get; init; }

        [JsonPropertyName("currentPhase")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string CurrentPhase { get; init; }

        [JsonPropertyName("currentHandNumber")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int CurrentHandNumber { get; init; }

        [JsonPropertyName("dealerPosition")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int DealerPosition { get; init; }

        [JsonPropertyName("ante")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? Ante { get; init; }

        [JsonPropertyName("smallBlind")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? SmallBlind { get; init; }

        [JsonPropertyName("bigBlind")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? BigBlind { get; init; }

        [JsonPropertyName("bringIn")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? BringIn { get; init; }

        [JsonPropertyName("smallBet")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? SmallBet { get; init; }

        [JsonPropertyName("bigBet")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? BigBet { get; init; }

        [JsonPropertyName("minBet")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? MinBet { get; init; }

        [JsonPropertyName("gameSettings")]
        public string GameSettings { get; init; }

        [JsonPropertyName("status")]
        public GameStatus Status { get; init; }

        [JsonPropertyName("currentPlayerIndex")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int CurrentPlayerIndex { get; init; }

        [JsonPropertyName("bringInPlayerIndex")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int BringInPlayerIndex { get; init; }

        [JsonPropertyName("currentDrawPlayerIndex")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int CurrentDrawPlayerIndex { get; init; }

        [JsonPropertyName("randomSeed")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? RandomSeed { get; init; }

        [JsonPropertyName("createdAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset CreatedAt { get; init; }

        [JsonPropertyName("updatedAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset UpdatedAt { get; init; }

        [JsonPropertyName("startedAt")]
        public System.DateTimeOffset? StartedAt { get; init; }

        [JsonPropertyName("endedAt")]
        public System.DateTimeOffset? EndedAt { get; init; }

        [JsonPropertyName("rowVersion")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string RowVersion { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record GetGamesResponse
    {
        [JsonConstructor]
        public GetGamesResponse(System.DateTimeOffset @createdAt, string @currentPhase, System.Guid @id, string @name, string @rowVersion, GameStatus @status)
        {
            this.Id = @id;
            this.Name = @name;
            this.CurrentPhase = @currentPhase;
            this.Status = @status;
            this.CreatedAt = @createdAt;
            this.RowVersion = @rowVersion;
        }

        [JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid Id { get; init; }

        [JsonPropertyName("name")]
        public string Name { get; init; }

        [JsonPropertyName("currentPhase")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string CurrentPhase { get; init; }

        [JsonPropertyName("status")]
        public GameStatus Status { get; init; }

        [JsonPropertyName("createdAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset CreatedAt { get; init; }

        [JsonPropertyName("rowVersion")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string RowVersion { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record PlayerInfo
    {
        [JsonConstructor]
        public PlayerInfo(string @name, int @startingChips)
        {
            this.Name = @name;
            this.StartingChips = @startingChips;
        }

        [JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; init; }

        [JsonPropertyName("startingChips")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int StartingChips { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record ProblemDetails
    {
        [JsonConstructor]
        public ProblemDetails(string @detail, string @instance, int? @status, string @title, string @type)
        {
            this.Type = @type;
            this.Title = @title;
            this.Status = @status;
            this.Detail = @detail;
            this.Instance = @instance;
        }

        [JsonPropertyName("type")]
        public string Type { get; init; }

        [JsonPropertyName("title")]
        public string Title { get; init; }

        [JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? Status { get; init; }

        [JsonPropertyName("detail")]
        public string Detail { get; init; }

        [JsonPropertyName("instance")]
        public string Instance { get; init; }

    }


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765


#nullable enable
namespace CardGames.Poker.Api.Clients
{
    using System;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Http.Resilience;
    using Refit;

    public static partial class IServiceCollectionExtensions
    {
        public static IServiceCollection ConfigureRefitClients(
            this IServiceCollection services, 
            Uri baseUrl, 
            Action<IHttpClientBuilder>? builder = default, 
            RefitSettings? settings = default)
        {
            var clientBuilderIFiveCardDrawApi = services
                .AddRefitClient<IFiveCardDrawApi>(settings)
                .ConfigureHttpClient(c => c.BaseAddress = baseUrl);

            clientBuilderIFiveCardDrawApi
                .AddStandardResilienceHandler(config =>
                {
                    config.Retry = new HttpRetryStrategyOptions
                    {
                        UseJitter = true,
                        MaxRetryAttempts = 3,
                        Delay = TimeSpan.FromSeconds(0.5)
                    };
                });

            builder?.Invoke(clientBuilderIFiveCardDrawApi);

            var clientBuilderICardGamesPokerApiApi = services
                .AddRefitClient<ICardGamesPokerApiApi>(settings)
                .ConfigureHttpClient(c => c.BaseAddress = baseUrl);

            clientBuilderICardGamesPokerApiApi
                .AddStandardResilienceHandler(config =>
                {
                    config.Retry = new HttpRetryStrategyOptions
                    {
                        UseJitter = true,
                        MaxRetryAttempts = 3,
                        Delay = TimeSpan.FromSeconds(0.5)
                    };
                });

            builder?.Invoke(clientBuilderICardGamesPokerApiApi);

            return services;
        }
    }
}