// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using CardGames.Poker.Api.Contracts;

#nullable enable annotations

namespace CardGames.Poker.Api.Clients
{
    /// <summary>CreateGame</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.7.0.0")]
    public partial interface IFiveCardDrawApi
    {
        /// <summary>CreateGame</summary>
        /// <remarks>Create a new game.</remarks>
        /// <returns>Created</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json, application/problem+json", "Content-Type: application/json")]
        [Post("/api/v1/games/five-card-draw")]
        Task<IApiResponse<System.Guid>> CreateGameAsync([Body] CreateGameCommand body, CancellationToken cancellationToken = default);

        /// <summary>GetGames</summary>
        /// <remarks>Retrieve a list of games.</remarks>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>OK</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json")]
        [Get("/api/v1/games/five-card-draw")]
        Task<IApiResponse<ICollection<GetGamesResponse>>> GetGamesAsync(CancellationToken cancellationToken = default);

        /// <summary>Start Hand</summary>
        /// <remarks>Starts a new hand by shuffling the deck, creating a fresh pot, and resetting all player states. This endpoint must be called before each hand to prepare the game for play. After calling this endpoint, the game transitions to the CollectingAntes phase.</remarks>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>OK</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json")]
        [Post("/api/v1/games/five-card-draw/{gameId}/hands")]
        Task<IApiResponse<StartHandSuccessful>> StartHandAsync(System.Guid gameId, CancellationToken cancellationToken = default);

        /// <summary>Collect Antes</summary>
        /// <remarks>Collects the mandatory ante bet from all players to seed the pot before dealing. Each player contributes the ante amount (or their remaining chips if short-stacked). After collection, the game transitions to the Dealing phase. Players with fewer chips than the ante will contribute their entire stack (going all-in on the ante).</remarks>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>OK</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json")]
        [Post("/api/v1/games/five-card-draw/{gameId}/hands/antes")]
        Task<IApiResponse<CollectAntesSuccessful>> CollectAntesAsync(System.Guid gameId, CancellationToken cancellationToken = default);

        /// <summary>Deal Hands</summary>
        /// <remarks>Deals five cards to each active player from the shuffled deck and initiates the first betting round. After dealing, the game transitions to the FirstBettingRound phase. This method deals 5 cards to each player who has not folded, resets all players' current bet amounts for the new betting round, and automatically starts the first betting round.</remarks>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>OK</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict</description>
        /// </item>
        /// <item>
        /// <term>422</term>
        /// <description>Unprocessable Entity</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json")]
        [Post("/api/v1/games/five-card-draw/{gameId}/hands/deal")]
        Task<IApiResponse<DealHandsSuccessful>> DealHandsAsync(System.Guid gameId, CancellationToken cancellationToken = default);

        /// <summary>GetGame</summary>
        /// <remarks>Retrieve a specific game by its identifier.</remarks>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>OK</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json")]
        [Get("/api/v1/games/five-card-draw/{gameId}")]
        Task<IApiResponse<GetGameResponse>> GetGameAsync(System.Guid gameId, CancellationToken cancellationToken = default);

        /// <summary>GetGamePlayers</summary>
        /// <remarks>Retrieve all players in a specific game.</remarks>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>OK</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json")]
        [Get("/api/v1/games/five-card-draw/{gameId}/players")]
        Task<IApiResponse<ICollection<GetGamePlayersResponse>>> GetGamePlayersAsync(System.Guid gameId, CancellationToken cancellationToken = default);

        /// <summary>GetCurrentPlayerTurn</summary>
        /// <remarks>Retrieve the current player's turn state for a specific game, including available actions.</remarks>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>OK</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json")]
        [Get("/api/v1/games/five-card-draw/{gameId}/current-turn")]
        Task<IApiResponse<GetCurrentPlayerTurnResponse>> GetCurrentPlayerTurnAsync(System.Guid gameId, CancellationToken cancellationToken = default);

        /// <summary>GetCurrentBettingRound</summary>
        /// <remarks>Retrieve the current betting round for a specific game.</remarks>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>OK</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json")]
        [Get("/api/v1/games/five-card-draw/{gameId}/betting-round")]
        Task<IApiResponse<GetCurrentBettingRoundResponse>> GetCurrentBettingRoundAsync(System.Guid gameId, CancellationToken cancellationToken = default);
    }

    /// <summary>No summary available</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.7.0.0")]
    public partial interface ICardGamesPokerApiApi
    {
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>OK</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: text/plain")]
        [Get("/")]
        Task<IApiResponse<string>> AnonymousAsync(CancellationToken cancellationToken = default);
    }

}

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace CardGames.Poker.Api.Contracts
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record AnteContribution
    {
        [JsonConstructor]
        public AnteContribution(int? @amount, string @playerName, int? @remainingChips, bool? @wentAllIn)
        {
            this.PlayerName = @playerName;
            this.Amount = @amount;
            this.RemainingChips = @remainingChips;
            this.WentAllIn = @wentAllIn;
        }

        [JsonPropertyName("playerName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string PlayerName { get; init; }

        [JsonPropertyName("amount")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? Amount { get; init; }

        [JsonPropertyName("remainingChips")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? RemainingChips { get; init; }

        [JsonPropertyName("wentAllIn")]
        public bool? WentAllIn { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record AvailableActionsResponse
    {
        [JsonConstructor]
        public AvailableActionsResponse(int @callAmount, bool @canAllIn, bool @canBet, bool @canCall, bool @canCheck, bool @canFold, bool @canRaise, int @maxBet, int @minBet, int @minRaise)
        {
            this.CanCheck = @canCheck;
            this.CanBet = @canBet;
            this.CanCall = @canCall;
            this.CanRaise = @canRaise;
            this.CanFold = @canFold;
            this.CanAllIn = @canAllIn;
            this.MinBet = @minBet;
            this.MaxBet = @maxBet;
            this.CallAmount = @callAmount;
            this.MinRaise = @minRaise;
        }

        [JsonPropertyName("canCheck")]
        public bool CanCheck { get; init; }

        [JsonPropertyName("canBet")]
        public bool CanBet { get; init; }

        [JsonPropertyName("canCall")]
        public bool CanCall { get; init; }

        [JsonPropertyName("canRaise")]
        public bool CanRaise { get; init; }

        [JsonPropertyName("canFold")]
        public bool CanFold { get; init; }

        [JsonPropertyName("canAllIn")]
        public bool CanAllIn { get; init; }

        [JsonPropertyName("minBet")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int MinBet { get; init; }

        [JsonPropertyName("maxBet")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int MaxBet { get; init; }

        [JsonPropertyName("callAmount")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int CallAmount { get; init; }

        [JsonPropertyName("minRaise")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int MinRaise { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum CardSuit
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Hearts")]
        Hearts = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"Diamonds")]
        Diamonds = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"Spades")]
        Spades = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"Clubs")]
        Clubs = 3,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum CardSymbol
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Deuce")]
        Deuce = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"Three")]
        Three = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"Four")]
        Four = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"Five")]
        Five = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"Six")]
        Six = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"Seven")]
        Seven = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"Eight")]
        Eight = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"Nine")]
        Nine = 7,

        [System.Runtime.Serialization.EnumMember(Value = @"Ten")]
        Ten = 8,

        [System.Runtime.Serialization.EnumMember(Value = @"Jack")]
        Jack = 9,

        [System.Runtime.Serialization.EnumMember(Value = @"Queen")]
        Queen = 10,

        [System.Runtime.Serialization.EnumMember(Value = @"King")]
        King = 11,

        [System.Runtime.Serialization.EnumMember(Value = @"Ace")]
        Ace = 12,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record CollectAntesSuccessful
    {
        [JsonConstructor]
        public CollectAntesSuccessful(ICollection<AnteContribution> @anteContributions, string @currentPhase, System.Guid? @gameId, int? @totalAntesCollected)
        {
            this.GameId = @gameId;
            this.TotalAntesCollected = @totalAntesCollected;
            this.CurrentPhase = @currentPhase;
            this.AnteContributions = @anteContributions;
        }

        [JsonPropertyName("gameId")]
        public System.Guid? GameId { get; init; }

        [JsonPropertyName("totalAntesCollected")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? TotalAntesCollected { get; init; }

        [JsonPropertyName("currentPhase")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string CurrentPhase { get; init; }

        [JsonPropertyName("anteContributions")]
        [System.ComponentModel.DataAnnotations.Required]
        public ICollection<AnteContribution> AnteContributions { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record CreateGameCommand
    {
        [JsonConstructor]
        public CreateGameCommand(int @ante, string @gameName, int @minBet, ICollection<PlayerInfo> @players)
        {
            this.GameName = @gameName;
            this.Ante = @ante;
            this.MinBet = @minBet;
            this.Players = @players;
        }

        [JsonPropertyName("gameName")]
        public string GameName { get; init; }

        [JsonPropertyName("ante")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int Ante { get; init; }

        [JsonPropertyName("minBet")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int MinBet { get; init; }

        [JsonPropertyName("players")]
        [System.ComponentModel.DataAnnotations.Required]
        public ICollection<PlayerInfo> Players { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record CurrentPlayerResponse
    {
        [JsonConstructor]
        public CurrentPlayerResponse(int @chipStack, int @currentBet, System.Guid @gameId, ICollection<DealtCard> @hand, bool @hasDrawnThisRound, bool @hasFolded, System.Guid @id, bool @isAllIn, bool @isConnected, bool @isSittingOut, System.DateTimeOffset @joinedAt, System.Guid @playerId, string @playerName, string @rowVersion, int @seatPosition, int @startingChips, GamePlayerStatus @status, int @totalContributedThisHand)
        {
            this.Id = @id;
            this.GameId = @gameId;
            this.PlayerId = @playerId;
            this.PlayerName = @playerName;
            this.SeatPosition = @seatPosition;
            this.ChipStack = @chipStack;
            this.StartingChips = @startingChips;
            this.CurrentBet = @currentBet;
            this.TotalContributedThisHand = @totalContributedThisHand;
            this.HasFolded = @hasFolded;
            this.IsAllIn = @isAllIn;
            this.IsConnected = @isConnected;
            this.IsSittingOut = @isSittingOut;
            this.HasDrawnThisRound = @hasDrawnThisRound;
            this.Status = @status;
            this.JoinedAt = @joinedAt;
            this.RowVersion = @rowVersion;
            this.Hand = @hand;
        }

        [JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid Id { get; init; }

        [JsonPropertyName("gameId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid GameId { get; init; }

        [JsonPropertyName("playerId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid PlayerId { get; init; }

        [JsonPropertyName("playerName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string PlayerName { get; init; }

        [JsonPropertyName("seatPosition")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int SeatPosition { get; init; }

        [JsonPropertyName("chipStack")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int ChipStack { get; init; }

        [JsonPropertyName("startingChips")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int StartingChips { get; init; }

        [JsonPropertyName("currentBet")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int CurrentBet { get; init; }

        [JsonPropertyName("totalContributedThisHand")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int TotalContributedThisHand { get; init; }

        [JsonPropertyName("hasFolded")]
        public bool HasFolded { get; init; }

        [JsonPropertyName("isAllIn")]
        public bool IsAllIn { get; init; }

        [JsonPropertyName("isConnected")]
        public bool IsConnected { get; init; }

        [JsonPropertyName("isSittingOut")]
        public bool IsSittingOut { get; init; }

        [JsonPropertyName("hasDrawnThisRound")]
        public bool HasDrawnThisRound { get; init; }

        [JsonPropertyName("status")]
        public GamePlayerStatus Status { get; init; }

        [JsonPropertyName("joinedAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset JoinedAt { get; init; }

        [JsonPropertyName("rowVersion")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string RowVersion { get; init; }

        [JsonPropertyName("hand")]
        [System.ComponentModel.DataAnnotations.Required]
        public ICollection<DealtCard> Hand { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record DealHandsSuccessful
    {
        [JsonConstructor]
        public DealHandsSuccessful(string @currentPhase, int? @currentPlayerIndex, string @currentPlayerName, System.Guid? @gameId, int? @handNumber, ICollection<PlayerDealtCards> @playerHands)
        {
            this.GameId = @gameId;
            this.CurrentPhase = @currentPhase;
            this.HandNumber = @handNumber;
            this.CurrentPlayerIndex = @currentPlayerIndex;
            this.CurrentPlayerName = @currentPlayerName;
            this.PlayerHands = @playerHands;
        }

        [JsonPropertyName("gameId")]
        public System.Guid? GameId { get; init; }

        [JsonPropertyName("currentPhase")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string CurrentPhase { get; init; }

        [JsonPropertyName("handNumber")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? HandNumber { get; init; }

        [JsonPropertyName("currentPlayerIndex")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? CurrentPlayerIndex { get; init; }

        [JsonPropertyName("currentPlayerName")]
        public string CurrentPlayerName { get; init; }

        [JsonPropertyName("playerHands")]
        [System.ComponentModel.DataAnnotations.Required]
        public ICollection<PlayerDealtCards> PlayerHands { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record DealtCard
    {
        [JsonConstructor]
        public DealtCard(int? @dealOrder, CardSuit? @suit, CardSymbol? @symbol)
        {
            this.Suit = @suit;
            this.Symbol = @symbol;
            this.DealOrder = @dealOrder;
        }

        [JsonPropertyName("suit")]
        public CardSuit? Suit { get; init; }

        [JsonPropertyName("symbol")]
        public CardSymbol? Symbol { get; init; }

        [JsonPropertyName("dealOrder")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? DealOrder { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum GamePlayerStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Active")]
        Active = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"Eliminated")]
        Eliminated = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"Left")]
        Left = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"Disconnected")]
        Disconnected = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"SittingOut")]
        SittingOut = 4,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum GameStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"WaitingForPlayers")]
        WaitingForPlayers = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"InProgress")]
        InProgress = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"BetweenHands")]
        BetweenHands = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"Completed")]
        Completed = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"Cancelled")]
        Cancelled = 4,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record GetCurrentBettingRoundResponse
    {
        [JsonConstructor]
        public GetCurrentBettingRoundResponse(System.DateTimeOffset? @completedAt, int @currentActorIndex, int @currentBet, System.Guid @gameId, int @handNumber, System.Guid @id, bool @isComplete, int @lastAggressorIndex, int @lastRaiseAmount, int @maxRaises, int @minBet, int @playersActed, int @playersInHand, int @raiseCount, int @roundNumber, string @rowVersion, System.DateTimeOffset @startedAt, string @street, int @totalPot)
        {
            this.Id = @id;
            this.GameId = @gameId;
            this.HandNumber = @handNumber;
            this.RoundNumber = @roundNumber;
            this.Street = @street;
            this.CurrentBet = @currentBet;
            this.MinBet = @minBet;
            this.TotalPot = @totalPot;
            this.RaiseCount = @raiseCount;
            this.MaxRaises = @maxRaises;
            this.LastRaiseAmount = @lastRaiseAmount;
            this.PlayersInHand = @playersInHand;
            this.PlayersActed = @playersActed;
            this.CurrentActorIndex = @currentActorIndex;
            this.LastAggressorIndex = @lastAggressorIndex;
            this.IsComplete = @isComplete;
            this.StartedAt = @startedAt;
            this.CompletedAt = @completedAt;
            this.RowVersion = @rowVersion;
        }

        [JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid Id { get; init; }

        [JsonPropertyName("gameId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid GameId { get; init; }

        [JsonPropertyName("handNumber")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int HandNumber { get; init; }

        [JsonPropertyName("roundNumber")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int RoundNumber { get; init; }

        [JsonPropertyName("street")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Street { get; init; }

        [JsonPropertyName("currentBet")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int CurrentBet { get; init; }

        [JsonPropertyName("minBet")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int MinBet { get; init; }

        [JsonPropertyName("totalPot")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int TotalPot { get; init; }

        [JsonPropertyName("raiseCount")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int RaiseCount { get; init; }

        [JsonPropertyName("maxRaises")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int MaxRaises { get; init; }

        [JsonPropertyName("lastRaiseAmount")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int LastRaiseAmount { get; init; }

        [JsonPropertyName("playersInHand")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int PlayersInHand { get; init; }

        [JsonPropertyName("playersActed")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int PlayersActed { get; init; }

        [JsonPropertyName("currentActorIndex")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int CurrentActorIndex { get; init; }

        [JsonPropertyName("lastAggressorIndex")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int LastAggressorIndex { get; init; }

        [JsonPropertyName("isComplete")]
        public bool IsComplete { get; init; }

        [JsonPropertyName("startedAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset StartedAt { get; init; }

        [JsonPropertyName("completedAt")]
        public System.DateTimeOffset? CompletedAt { get; init; }

        [JsonPropertyName("rowVersion")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string RowVersion { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record GetCurrentPlayerTurnResponse
    {
        [JsonConstructor]
        public GetCurrentPlayerTurnResponse(AvailableActionsResponse @availableActions, CurrentPlayerResponse @player)
        {
            this.Player = @player;
            this.AvailableActions = @availableActions;
        }

        [JsonPropertyName("player")]
        [System.ComponentModel.DataAnnotations.Required]
        public CurrentPlayerResponse Player { get; init; }

        [JsonPropertyName("availableActions")]
        public AvailableActionsResponse AvailableActions { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record GetGamePlayersResponse
    {
        [JsonConstructor]
        public GetGamePlayersResponse(int @chipStack, int @currentBet, System.Guid @gameId, ICollection<DealtCard> @hand, bool @hasDrawnThisRound, bool @hasFolded, System.Guid @id, bool @isAllIn, bool @isConnected, bool @isSittingOut, System.DateTimeOffset @joinedAt, System.Guid @playerId, string @playerName, string @rowVersion, int @seatPosition, int @startingChips, GamePlayerStatus @status, int @totalContributedThisHand)
        {
            this.Id = @id;
            this.GameId = @gameId;
            this.PlayerId = @playerId;
            this.PlayerName = @playerName;
            this.SeatPosition = @seatPosition;
            this.ChipStack = @chipStack;
            this.StartingChips = @startingChips;
            this.CurrentBet = @currentBet;
            this.TotalContributedThisHand = @totalContributedThisHand;
            this.HasFolded = @hasFolded;
            this.IsAllIn = @isAllIn;
            this.IsConnected = @isConnected;
            this.IsSittingOut = @isSittingOut;
            this.HasDrawnThisRound = @hasDrawnThisRound;
            this.Status = @status;
            this.JoinedAt = @joinedAt;
            this.RowVersion = @rowVersion;
            this.Hand = @hand;
        }

        [JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid Id { get; init; }

        [JsonPropertyName("gameId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid GameId { get; init; }

        [JsonPropertyName("playerId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid PlayerId { get; init; }

        [JsonPropertyName("playerName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string PlayerName { get; init; }

        [JsonPropertyName("seatPosition")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int SeatPosition { get; init; }

        [JsonPropertyName("chipStack")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int ChipStack { get; init; }

        [JsonPropertyName("startingChips")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int StartingChips { get; init; }

        [JsonPropertyName("currentBet")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int CurrentBet { get; init; }

        [JsonPropertyName("totalContributedThisHand")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int TotalContributedThisHand { get; init; }

        [JsonPropertyName("hasFolded")]
        public bool HasFolded { get; init; }

        [JsonPropertyName("isAllIn")]
        public bool IsAllIn { get; init; }

        [JsonPropertyName("isConnected")]
        public bool IsConnected { get; init; }

        [JsonPropertyName("isSittingOut")]
        public bool IsSittingOut { get; init; }

        [JsonPropertyName("hasDrawnThisRound")]
        public bool HasDrawnThisRound { get; init; }

        [JsonPropertyName("status")]
        public GamePlayerStatus Status { get; init; }

        [JsonPropertyName("joinedAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset JoinedAt { get; init; }

        [JsonPropertyName("rowVersion")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string RowVersion { get; init; }

        [JsonPropertyName("hand")]
        [System.ComponentModel.DataAnnotations.Required]
        public ICollection<DealtCard> Hand { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record GetGameResponse
    {
        [JsonConstructor]
        public GetGameResponse(int? @ante, int? @bigBet, int? @bigBlind, int? @bringIn, int @bringInPlayerIndex, System.DateTimeOffset @createdAt, int @currentDrawPlayerIndex, int @currentHandNumber, string @currentPhase, int @currentPlayerIndex, int @dealerPosition, System.DateTimeOffset? @endedAt, string @gameSettings, System.Guid @gameTypeId, System.Guid @id, int? @minBet, string @name, int? @randomSeed, string @rowVersion, int? @smallBet, int? @smallBlind, System.DateTimeOffset? @startedAt, GameStatus @status, System.DateTimeOffset @updatedAt)
        {
            this.Id = @id;
            this.GameTypeId = @gameTypeId;
            this.Name = @name;
            this.CurrentPhase = @currentPhase;
            this.CurrentHandNumber = @currentHandNumber;
            this.DealerPosition = @dealerPosition;
            this.Ante = @ante;
            this.SmallBlind = @smallBlind;
            this.BigBlind = @bigBlind;
            this.BringIn = @bringIn;
            this.SmallBet = @smallBet;
            this.BigBet = @bigBet;
            this.MinBet = @minBet;
            this.GameSettings = @gameSettings;
            this.Status = @status;
            this.CurrentPlayerIndex = @currentPlayerIndex;
            this.BringInPlayerIndex = @bringInPlayerIndex;
            this.CurrentDrawPlayerIndex = @currentDrawPlayerIndex;
            this.RandomSeed = @randomSeed;
            this.CreatedAt = @createdAt;
            this.UpdatedAt = @updatedAt;
            this.StartedAt = @startedAt;
            this.EndedAt = @endedAt;
            this.RowVersion = @rowVersion;
        }

        [JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid Id { get; init; }

        [JsonPropertyName("gameTypeId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid GameTypeId { get; init; }

        [JsonPropertyName("name")]
        public string Name { get; init; }

        [JsonPropertyName("currentPhase")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string CurrentPhase { get; init; }

        [JsonPropertyName("currentHandNumber")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int CurrentHandNumber { get; init; }

        [JsonPropertyName("dealerPosition")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int DealerPosition { get; init; }

        [JsonPropertyName("ante")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? Ante { get; init; }

        [JsonPropertyName("smallBlind")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? SmallBlind { get; init; }

        [JsonPropertyName("bigBlind")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? BigBlind { get; init; }

        [JsonPropertyName("bringIn")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? BringIn { get; init; }

        [JsonPropertyName("smallBet")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? SmallBet { get; init; }

        [JsonPropertyName("bigBet")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? BigBet { get; init; }

        [JsonPropertyName("minBet")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? MinBet { get; init; }

        [JsonPropertyName("gameSettings")]
        public string GameSettings { get; init; }

        [JsonPropertyName("status")]
        public GameStatus Status { get; init; }

        [JsonPropertyName("currentPlayerIndex")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int CurrentPlayerIndex { get; init; }

        [JsonPropertyName("bringInPlayerIndex")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int BringInPlayerIndex { get; init; }

        [JsonPropertyName("currentDrawPlayerIndex")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int CurrentDrawPlayerIndex { get; init; }

        [JsonPropertyName("randomSeed")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? RandomSeed { get; init; }

        [JsonPropertyName("createdAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset CreatedAt { get; init; }

        [JsonPropertyName("updatedAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset UpdatedAt { get; init; }

        [JsonPropertyName("startedAt")]
        public System.DateTimeOffset? StartedAt { get; init; }

        [JsonPropertyName("endedAt")]
        public System.DateTimeOffset? EndedAt { get; init; }

        [JsonPropertyName("rowVersion")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string RowVersion { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record GetGamesResponse
    {
        [JsonConstructor]
        public GetGamesResponse(System.DateTimeOffset @createdAt, string @currentPhase, System.Guid @id, string @name, string @rowVersion, GameStatus @status)
        {
            this.Id = @id;
            this.Name = @name;
            this.CurrentPhase = @currentPhase;
            this.Status = @status;
            this.CreatedAt = @createdAt;
            this.RowVersion = @rowVersion;
        }

        [JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid Id { get; init; }

        [JsonPropertyName("name")]
        public string Name { get; init; }

        [JsonPropertyName("currentPhase")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string CurrentPhase { get; init; }

        [JsonPropertyName("status")]
        public GameStatus Status { get; init; }

        [JsonPropertyName("createdAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset CreatedAt { get; init; }

        [JsonPropertyName("rowVersion")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string RowVersion { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record PlayerDealtCards
    {
        [JsonConstructor]
        public PlayerDealtCards(ICollection<DealtCard> @cards, string @playerName, int? @seatPosition)
        {
            this.PlayerName = @playerName;
            this.SeatPosition = @seatPosition;
            this.Cards = @cards;
        }

        [JsonPropertyName("playerName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string PlayerName { get; init; }

        [JsonPropertyName("seatPosition")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? SeatPosition { get; init; }

        [JsonPropertyName("cards")]
        [System.ComponentModel.DataAnnotations.Required]
        public ICollection<DealtCard> Cards { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record PlayerInfo
    {
        [JsonConstructor]
        public PlayerInfo(string @name, int @startingChips)
        {
            this.Name = @name;
            this.StartingChips = @startingChips;
        }

        [JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; init; }

        [JsonPropertyName("startingChips")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int StartingChips { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record ProblemDetails
    {
        [JsonConstructor]
        public ProblemDetails(string @detail, string @instance, int? @status, string @title, string @type)
        {
            this.Type = @type;
            this.Title = @title;
            this.Status = @status;
            this.Detail = @detail;
            this.Instance = @instance;
        }

        [JsonPropertyName("type")]
        public string Type { get; init; }

        [JsonPropertyName("title")]
        public string Title { get; init; }

        [JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? Status { get; init; }

        [JsonPropertyName("detail")]
        public string Detail { get; init; }

        [JsonPropertyName("instance")]
        public string Instance { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record StartHandSuccessful
    {
        [JsonConstructor]
        public StartHandSuccessful(int? @activePlayerCount, string @currentPhase, System.Guid? @gameId, int? @handNumber)
        {
            this.GameId = @gameId;
            this.HandNumber = @handNumber;
            this.CurrentPhase = @currentPhase;
            this.ActivePlayerCount = @activePlayerCount;
        }

        [JsonPropertyName("gameId")]
        public System.Guid? GameId { get; init; }

        [JsonPropertyName("handNumber")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? HandNumber { get; init; }

        [JsonPropertyName("currentPhase")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string CurrentPhase { get; init; }

        [JsonPropertyName("activePlayerCount")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^-?(?:0|[1-9]\d*)$")]
        public int? ActivePlayerCount { get; init; }

    }


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765


#nullable enable
namespace CardGames.Poker.Api.Clients
{
    using System;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Http.Resilience;
    using Refit;

    public static partial class IServiceCollectionExtensions
    {
        public static IServiceCollection ConfigureRefitClients(
            this IServiceCollection services, 
            Uri baseUrl, 
            Action<IHttpClientBuilder>? builder = default, 
            RefitSettings? settings = default)
        {
            var clientBuilderIFiveCardDrawApi = services
                .AddRefitClient<IFiveCardDrawApi>(settings)
                .ConfigureHttpClient(c => c.BaseAddress = baseUrl);

            clientBuilderIFiveCardDrawApi
                .AddStandardResilienceHandler(config =>
                {
                    config.Retry = new HttpRetryStrategyOptions
                    {
                        UseJitter = true,
                        MaxRetryAttempts = 3,
                        Delay = TimeSpan.FromSeconds(0.5)
                    };
                });

            builder?.Invoke(clientBuilderIFiveCardDrawApi);

            var clientBuilderICardGamesPokerApiApi = services
                .AddRefitClient<ICardGamesPokerApiApi>(settings)
                .ConfigureHttpClient(c => c.BaseAddress = baseUrl);

            clientBuilderICardGamesPokerApiApi
                .AddStandardResilienceHandler(config =>
                {
                    config.Retry = new HttpRetryStrategyOptions
                    {
                        UseJitter = true,
                        MaxRetryAttempts = 3,
                        Delay = TimeSpan.FromSeconds(0.5)
                    };
                });

            builder?.Invoke(clientBuilderICardGamesPokerApiApi);

            return services;
        }
    }
}